"""1st revision

Revision ID: a4234bb34af9
Revises: 
Create Date: 2023-08-02 12:23:43.492154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4234bb34af9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_symptom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('symptom_code', sa.String(), nullable=False),
    sa.Column('symptom_name', sa.String(), nullable=False),
    sa.Column('symptom_diagnostic', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('business_symptons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_symptons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symptom_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symptom_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('symptom_diagnostic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='business_symptons_pkey')
    )
    op.drop_table('business_symptom')
    # ### end Alembic commands ###
